# Stage 1 -  create react app first
FROM node:16.14.0 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/
COPY ./yarn.lock  /app/
RUN yarn install 
COPY . /app
RUN yarn build 

#stage 2 - build the final image and copy the react files
FROM nginx:stable
COPY --from=build app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf  /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]